export const GET_MOVIES_FETCH_START = 'GET_MOVIES_FETCH_START';
export const GET_MOVIES_FETCH_SUCCESS = 'GET_MOVIES_FETCH_SUCCESS';
export const GET_MOVIES_FETCH_FAIL = 'GET_MOVIES_FETCH_FAIL';

export const SEARCH_MOVIES_FETCH_SUCCESS = 'SEARCH_MOVIES_FETCH_SUCCESS';

export const SET_SELECTEDMOVIE_ID = 'SET_SELECTEDMOVIE_ID';

export const GET_MOVIE_REVIEWS = 'GET_MOVIE_REVIEWS';
export const GET_MOVIE_VIDEO = 'GET_MOVIE_VIDEO';
export const GET_SIMILAR_MOVIES = 'GET_SIMILAR_MOVIES';

export const GET_GENRES_FETCH_START = 'GET_GENRES_FETCH_START';
export const GET_GENRES_FETCH_SUCCESS = 'GET_GENRES_FETCH_SUCCESS';
export const GET_GENRES_FETCH_FAIL = 'GET_GENRES_FETCH_FAIL';
